// <auto-generated />
namespace DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class category_id1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(category_id1));
        
        string IMigrationMetadata.Id
        {
            get { return "202108160635097_category_id1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
